using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SNEngine.API.Generators;

/// <summary>
/// Roslyn Source Generator for SNEngine JS facade.
/// 
/// It only emits C# source (a string constant containing the JS).
/// Physical .js files are not written by the generator itself (forbidden + bad for incremental builds).
/// 
/// If you want a visible .js file after build, add an MSBuild Target in SNEngine.API.csproj
/// that extracts SNEngineJSBindings.GeneratedFacade and writes it to bin/js/.
/// </summary>
[Generator]
public class SNEngineJSGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationProvider = context.CompilationProvider;

        var apiClasses = compilationProvider
            .SelectMany((compilation, ct) =>
            {
                var result = new List<ApiClassInfo>();

                foreach (var tree in compilation.SyntaxTrees)
                {
                    var semanticModel = compilation.GetSemanticModel(tree);
                    var root = tree.GetRoot(ct);

                    foreach (var cls in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
                    {
                        if (!cls.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PublicKeyword)))
                            continue;

                        if (!cls.Identifier.Text.EndsWith("API", StringComparison.Ordinal))
                            continue;

                        var classSymbol = semanticModel.GetDeclaredSymbol(cls, ct) as INamedTypeSymbol;
                        if (classSymbol == null) continue;

                        var methods = new List<ApiMethodInfo>();

                        foreach (var methodSyntax in cls.Members.OfType<MethodDeclarationSyntax>())
                        {
                            if (!methodSyntax.Modifiers.Any(mod => mod.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PublicKeyword)) ||
                                !methodSyntax.Modifiers.Any(mod => mod.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StaticKeyword)))
                                continue;

                            var methodSymbol = semanticModel.GetDeclaredSymbol(methodSyntax, ct) as IMethodSymbol;
                            if (methodSymbol == null) continue;

                            // Respect [JSExclude] attribute
                            bool isExcluded = methodSymbol.GetAttributes()
                                .Any(attr => attr.AttributeClass?.ToDisplayString() == "SNEngine.API.JSExcludeAttribute");

                            if (isExcluded)
                                continue;

                            methods.Add(new ApiMethodInfo
                            {
                                Name = methodSymbol.Name,
                                ParameterCount = methodSymbol.Parameters.Length
                            });
                        }

                        if (methods.Any())
                        {
                            result.Add(new ApiClassInfo
                            {
                                ClassName = classSymbol.Name,
                                Methods = methods
                            });
                        }
                    }
                }

                return result;
            })
            .Where(info => info.Methods.Any())
            .Collect();

        context.RegisterSourceOutput(apiClasses, (spc, classes) =>
        {
            if (!classes.Any()) return;

            string js = BuildJs(classes);
            string csharp = BuildCSharp(js);

            spc.AddSource("SNEngineJSBindings.g.cs", SourceText.From(csharp, Encoding.UTF8));
        });
    }

    private string BuildJs(IEnumerable<ApiClassInfo> apiClasses)
    {
        var js = new StringBuilder();
        js.AppendLine("// <auto-generated/>");
        js.AppendLine("// Built by SNEngine.API.Generators at dotnet build time");
        js.AppendLine("(function(){");
        js.AppendLine("  const sn = window.sn || {};");
        js.AppendLine("  window.sn = sn;");
        js.AppendLine("  window.SNEngine = sn;");
        js.AppendLine();

        foreach (var api in apiClasses)
        {
            // Skip editor/tooling APIs in the runtime JS facade
            if (api.ClassName == "ProjectAPI")
                continue;

            string shortName = api.ClassName.Replace("API", ""); // Background, Character, etc.

            js.AppendLine($"  sn.{shortName} = sn.{shortName} || {{}};");
            js.AppendLine($"  // {api.ClassName}");

            foreach (var m in api.Methods)
            {
                js.Append($"  sn.{shortName}.{m.Name} = function(");
                for (int i = 0; i < m.ParameterCount; i++) { if (i > 0) js.Append(", "); js.Append("a" + i); }
                js.AppendLine("){");
                js.AppendLine("    if (window.SNEngineHost && typeof SNEngineHost.call === 'function') {");
                js.AppendLine($"      SNEngineHost.call('{api.ClassName}.{m.Name}', Array.prototype.slice.call(arguments));");
                js.AppendLine("    }");
                js.AppendLine("  };");
            }
            js.AppendLine();
        }

        js.AppendLine("  console.log('[SNEngine] JS facade ready');");
        js.AppendLine("})();");
        return js.ToString();
    }

    private string BuildCSharp(string js)
    {
        string escaped = js.Replace("\"", "\"\"");
        return $@"// <auto-generated/>
namespace SNEngine.API;
public static partial class SNEngineJSBindings {{
    public const string GeneratedFacade = @""{escaped}"";
    public static string GetGeneratedFacade() => GeneratedFacade;
}}";
    }

    private sealed class ApiClassInfo { public string ClassName { get; set; } = ""; public List<ApiMethodInfo> Methods { get; set; } = new(); }
    private sealed class ApiMethodInfo { public string Name { get; set; } = ""; public int ParameterCount { get; set; } }
}
