<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SNEngine.API\SNEngine.API.csproj" />
    <ProjectReference Include="..\SNEngine.Core\SNEngine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\bg\classroom_day.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
