using System;
using System.Linq;
using System.Reflection;

namespace SNEngine.API;

/// <summary>
/// Host object that is exposed to JavaScript inside Ultralight views as <c>window.SNEngineHost</c>.
/// 
/// JavaScript code (generated by the source generator) calls it like this:
/// <code>
/// SNEngineHost.call('BackgroundAPI.Show', ['classroom_day']);
/// SNEngineHost.call('CharacterAPI.Show', ['yuki', 'happy']);
/// </code>
/// 
/// This class performs the actual dispatch to the corresponding static methods
/// in BackgroundAPI, CharacterAPI, etc.
/// </summary>
public static class SNEngineHostAPI
{
    /// <summary>
    /// Main entry point called from JavaScript.
    /// </summary>
    /// <param name="methodName">Full method name, e.g. "BackgroundAPI.Show" or "CharacterAPI.Show"</param>
    /// <param name="args">Arguments passed from JavaScript (will be converted)</param>
    /// <returns>Result of the call (currently always null for fire-and-forget style)</returns>
    public static object? Call(string methodName, object?[]? args)
    {
        if (string.IsNullOrWhiteSpace(methodName))
        {
            Console.WriteLine("[SNEngineHost] Empty method name");
            return null;
        }

        try
        {
            var parts = methodName.Split('.');
            if (parts.Length != 2)
            {
                Console.WriteLine($"[SNEngineHost] Invalid method name format: {methodName}");
                return null;
            }

            string className = parts[0];
            string method = parts[1];

            var apiAssembly = typeof(SNEngineHostAPI).Assembly;

            // Более надёжный поиск типа
            var type = apiAssembly.GetType($"SNEngine.API.{className}", false, true)
                    ?? apiAssembly.GetTypes()
                        .FirstOrDefault(t => t.Name.Equals(className, StringComparison.OrdinalIgnoreCase));

            if (type == null)
            {
                Console.WriteLine($"[SNEngineHost] Type not found: {className}");
                return null;
            }

            var methodInfo = type.GetMethod(method, BindingFlags.Public | BindingFlags.Static);
            if (methodInfo == null)
            {
                Console.WriteLine($"[SNEngineHost] Method not found: {methodName}");
                return null;
            }

            object?[] convertedArgs = ConvertArguments(methodInfo, args);
            var result = methodInfo.Invoke(null, convertedArgs);

            return result;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[SNEngineHost] Error calling '{methodName}': {ex.Message}");
            return null;
        }
    }

    private static object?[] ConvertArguments(MethodInfo method, object?[]? rawArgs)
    {
        var parameters = method.GetParameters();
        var result = new object?[parameters.Length];

        for (int i = 0; i < parameters.Length; i++)
        {
            if (rawArgs == null || i >= rawArgs.Length)
            {
                // Use default value if available
                result[i] = parameters[i].HasDefaultValue ? parameters[i].DefaultValue : null;
                continue;
            }

            object? value = rawArgs[i];
            var targetType = parameters[i].ParameterType;

            try
            {
                if (value == null)
                {
                    result[i] = null;
                    continue;
                }

                // Basic conversions from JS (which usually comes as string/number/bool)
                if (targetType == typeof(string))
                {
                    result[i] = value.ToString();
                }
                else if (targetType == typeof(float) || targetType == typeof(double))
                {
                    result[i] = Convert.ToDouble(value);
                }
                else if (targetType == typeof(int))
                {
                    result[i] = Convert.ToInt32(value);
                }
                else if (targetType == typeof(bool))
                {
                    result[i] = Convert.ToBoolean(value);
                }
                else if (targetType.IsEnum)
                {
                    result[i] = Enum.Parse(targetType, value.ToString() ?? "", true);
                }
                else
                {
                    // Fallback - try direct cast or leave as is
                    result[i] = Convert.ChangeType(value, targetType);
                }
            }
            catch
            {
                result[i] = value; // last resort
            }
        }

        return result;
    }
}
